/// custom event names
/// used to exchange messages between injected script and content script
export const EVENT_NAMES = {
  GENERATE_WALLET_KEY: 'ZKOPRU#GENERATE_WALLET_KEY',
  WALLET_KEY_GENERATED: 'ZKOPRU#WALLET_KEY_GENERATED',
  DEPOSIT_ETH: 'ZKOPRU#DEPOSIT_ETH',
  SEND_TX: 'ZKOPRU#SEND_TX',

  CONNECTED: 'ZKOPRU#CONNECTED',

  SET_PROVIDER: 'ZKOPRU#SET_PROVIDER',

  PROVIDER_CONNECTED: 'ZKOPRU#PROVIDER_CONNECTED'
} as const

export const PROVIDER_EVENT_NAMES = {
  CONFIRM_POPUP: 'ZKOPRU_PROVIDER#CONFIRM_POPUP',
  CONNECT: 'ZKOPRU_PROVIDER#CONNECT',
  BALANCE_REQUEST: 'ZKOPRU_PROVIDER#BALANCE_REQUEST',
  BALANCE_RESPONSE: 'ZKOPRU_PROVIDER#BALANCE_RESPONSE',
  ADDRESS_REQUEST: 'ZKOPRU_PROVIDER#ADDRESS_REQUEST',
  ADDRES_RESPONSE: 'ZKOPRU_PROVIDER#ADDRESS_RESPONSE'
} as const
