/* eslint-disable react/jsx-key */
import { ComponentStory, ComponentMeta } from '@storybook/react'

import Button from '.'
import { AddCircleLine } from '../common/icons'

const iconOpts = new Map<string, JSX.Element>([
  ['AddCircleLine', <AddCircleLine />]
])

export default {
  title: 'Buttons/Regular',
  component: Button,
  argTypes: {
    children: { description: 'Label of the button', control: 'text' },
    icon: {
      description:
        'An icon to display on the button. We use SVG components generated by svgr to render the icons.',
      options: ['None', ...Array.from(iconOpts.keys())],
      mapping: {
        None: undefined,
        ...Object.fromEntries(iconOpts.entries())
      },
      control: {
        type: 'select'
      }
    }
  }
} as ComponentMeta<typeof Button>

const Template: ComponentStory<typeof Button> = (args) => {
  const { children, icon, variant, ...rest } = args
  return (
    <Button {...rest} variant={variant || 'filled'} icon={icon}>
      {children}
    </Button>
  )
}

export const Filled = Template.bind({})
Filled.args = {
  children: 'Main button'
}

export const Ghost = Template.bind({})
Ghost.args = {
  variant: 'ghost',
  children: 'Ghost button'
}
